version: "3"

services:
  phpapp:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: awssecretsmanager
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: awssecretsnginx
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
